using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EDIFACTMediator.Utils
{
    using System;
    using System.Collections.Generic;

    public static class CodeListAgency
    {
        private static readonly Dictionary<int, string> CodeList = new Dictionary<int, string>
    {
        { 1, "CCC (Customs Co-operation Council)" },
        { 2, "CEC (Commission of the European Communities)" },
        { 3, "IATA (International Air Transport Association)" },
        { 4, "ICC (International Chamber of Commerce)" },
        { 5, "ISO (International Organization for Standardization)" },
        { 6, "UN/ECE (United Nations - Economic Commission for Europe)" },
        { 7, "CEFIC (Conseil Europeen des Federations de l'Industrie Chimique)" },
        { 8, "EDIFICE (EDI Forum for companies with Interest in Computing and Electronics)" },
        { 9, "EAN (International Article Numbering association)" },
        { 10, "ODETTE (Organization for Data Exchange through Tele-Transmission in Europe)" },
        { 11, "Lloyd's register of shipping" },
        { 12, "UIC (International union of railways)" },
        { 13, "ICAO (International Civil Aviation Organisation)" },
        { 14, "ICS (International Chamber of Shipping)" },
        { 15, "RINET (Reinsurance and Insurance Network)" },
        { 16, "DUNS (Dun & Bradstreet)" },
        { 17, "S.W.I.F.T. (Society for Worldwide Interbank Financial Telecommunications s.c.)" },
        { 18, "Conventions on SAD and transit (EC and EFTA)" },
        { 19, "FRRC (Federal Reserve Routing Code)" },
        { 20, "BIC (Bureau International des Containeurs)" },
        { 21, "Assigned by transport company" },
        { 22, "US, ISA (Information Systems Agreement)" },
        { 23, "FR, EDITRANSPORT" },
        { 24, "AU, ROA (Railways of Australia)" },
        { 25, "EDITEX (Europe)" },
        { 26, "NL, Foundation Uniform Transport Code" },
        { 27, "US, FDA (Food and Drug Administration)" },
        { 28, "EDITEUR (European book sector electronic data interchange group)" },
        { 29, "GB, FLEETNET" },
        { 30, "GB, ABTA (Association of British Travel Agencies)" },
        { 31, "FI, Finish State Railway" },
        { 32, "PL, Polish State Railway" },
        { 33, "BG, Bulgaria State Railway" },
        { 34, "RO, Rumanian State Railway" },
        { 35, "CZ, Tchechian State Railway" },
        { 36, "HU, Hungarian State Railway" },
        { 37, "GB, British Railways" },
        { 38, "ES, Spanish National Railway" },
        { 39, "SE, Swedish State Railway" },
        { 40, "NO, Norwegian State Railway" },
        { 41, "DE, German Railway" },
        { 42, "AT, Austrian Federal Railways" },
        { 43, "LU, Luxembourg National Railway Company" },
        { 44, "IT, Italian State Railways" },
        { 45, "NL, Netherlands Railways" },
        { 46, "CH, Swiss Federal Railways" },
        { 47, "DK, Danish State Railways" },
        { 48, "FR, French National Railway Company" },
        { 49, "BE, Belgian National Railway Company" },
        { 50, "PT, Portuguese Railways" },
        { 51, "SK, Slovacian State Railways" },
        { 52, "IE, Irish Transport Company" },
        { 53, "FIATA (International Federation of Freight Forwarders Associations)" },
        { 54, "IMO (International Maritime Organisation)" },
        { 55, "US, DOT (United States Department of Transportation)" },
        { 56, "TW, Trade-van" },
        { 57, "TW, Chinese Taipei Customs" },
        { 58, "EUROFER (European steel organisation - EDI project for the European steel industry)" },
        { 59, "DE, EDIBAU" },
        { 60, "Assigned by national trade agency" },
        { 61, "Association Europeenne des Constructeurs de Materiel Aerospatial (AECMA)" },
        { 62, "US, DIstilled Spirits Council of the United States (DISCUS)" },
        { 63, "North Atlantic Treaty Organization (NATO)" },
        { 64, "FR, EDIFRANCE" },
        { 65, "FR, GENCOD" },
        { 66, "MY, Malaysian Customs and Excise" },
        { 67, "MY, Malaysia Central Bank" },
        { 68, "US, Bureau of Alcohol, Tobacco and Firearms (BATF)" },
        { 69, "US, National Alcohol Beverage Control Association (NABCA)" },
        { 70, "MY, Dagang.Net" },
        { 86, "Assigned by party originating the message" },
        { 87, "Assigned by carrier" },
        { 88, "Assigned by owner of operation" },
        { 89, "Assigned by distributor" },
        { 90, "Assigned by manufacturer" },
        { 91, "Assigned by seller or seller's agent" },
        { 92, "Assigned by buyer or buyer's agent" },
        { 93, "AT, Austrian Customs" },
        { 94, "AT, Austrian PTT" },
        { 95, "AU, Australian Customs Services" },
        { 96, "CA, Revenue Canada, Customs and Excise" },
        { 97, "CH, Administration federale des contributions" },
        { 98, "CH, Direction generale des douanes" },
        { 99, "CH, Division des importations et exportations, OFAEE" },
        { 100, "CH, Entreprise des PTT" },
        { 101, "CH, Carbura" },
        { 102, "CH, Centrale suisse pour l'importation du charbon" },
        { 103, "CH, Office fiduciaire des importateurs de denrees alimentaires" },
        { 104, "CH, Association suisse code des articles" },
        { 105, "DK, Ministry of taxation, Central Customs and Tax Administration" },
        { 106, "FR, Direction generale des douanes et droits indirects" },
        { 107, "FR, INSEE" },
        { 108, "FR, Banque de France" },
        { 109, "GB, H.M. Customs & Excise" },
        { 110, "IE, Revenue Commissionners, Customs AEP project" },
        { 111, "US, U.S. Customs Service" },
        { 112, "US, U.S. Census Bureau" },
        { 113, "US, UPC (Uniform product code)" },
        { 114, "US, ABA (American Bankers Association)" },
        { 115, "US, DODAAC (Department Of Defense Active Agency Code)" },
        { 116, "US, ANSI ASC X12" },
        { 117, "AT, Geldausgabeautomaten-Service Gesellschaft m.b.H." },
        { 118, "SE, Svenska Bankfoereningen" },
        { 119, "IT, Associazione Bancaria Italiana" },
        { 120, "IT, Socieata' Interbancaria per l'Automazione" },
        { 121, "CH, Telekurs AG" },
        { 122, "CH, Swiss Securities Clearing Corporation" },
        { 123, "NO, Norwegian Interbank Research Organization" },
        { 124, "NO, Norwegian Bankers Ass." },
        { 125, "FI, The Finnish Bankers' Association" },
        { 126, "US, NCCMA (Account Analysis Codes)" },
        { 128, "BE, Belgian Bankers' Association" },
        { 129, "BE, Belgian Ministry of Finance" },
        { 130, "DK, PBS (Pengainstitutternes Betalings Service)" },
        { 131, "DE, German Bankers Association" },
        { 132, "GB, BACS Limited" },
        { 133, "GB, Association for Payment Clearing Services" },
        { 134, "GB, CHAPS and Town Clearing Company Ltd." },
        { 135, "GB, The Clearing House" },
        { 136, "GB, Article Number Association (UK) Limited" },
        { 137, "AT, Verband oesterreichischer Banken und Bankiers" },
        { 138, "FR, CFONB (Comite francais d'organ. et de normalisation bancaires)" },
        { 139, "UPU (Universal Postal Union)" },
        { 140, "CEC (Commission of the European Communities), DG/XXI-01" },
        { 141, "CEC (Commission of the European Communities), DG/XXI-B-1" },
        { 142, "CEC (Commission of the European Communities), DG/XXXIV" },
        { 143, "NZ, New Zealand Customs" },
        { 144, "NL, Netherlands Customs" },
        { 145, "SE, Swedish Customs" },
        { 146, "DE, German Customs" },
        { 147, "BE, Belgian Customs" },
        { 148, "ES, Spanish Customs" },
        { 149, "IL, Israel Customs" },
        { 150, "HK, Hong Kong Customs" },
        { 151, "JP, Japan Customs" },
        { 152, "SA, Saudi Arabia Customs" },
        { 153, "IT, Italian Customs" },
        { 154, "GR, Greek Customs" },
        { 155, "PT, Portuguese Customs" },
        { 156, "LU, Luxembourg Customs" },
        { 157, "NO, Norwegian Customs" },
        { 158, "FI, Finnish Customs" },
        { 159, "IS, Iceland Customs" },
        { 160, "LI, Liechtenstein authority" },
        { 161, "UNCTAD (United Nations - Conference on Trade And Development)" },
        { 162, "CEC (Commission of the European Communities), DG/XIII-D-5" },
        { 163, "US, FMC (Federal Maritime Commission)" },
        { 164, "US, DEA (Drug Enforcement Agency)" },
        { 165, "US, DCI (Distribution Codes, INC.)" },
        { 166, "US, National Motor Freight Classification Association" },
        { 167, "US, AIAG (Automotive Industry Action Group)" },
        { 168, "US, FIPS (Federal Information Publishing Standard)" },
        { 169, "CA, SCC (Standards Council of Canada)" },
        { 170, "CA, CPA (Canadian Payment Association)" },
        { 171, "NL, Bank Girocentrale BV" },
        { 172, "NL, BEANET BV" },
        { 173, "NO, NORPRO" },
        { 174, "DE, DIN (Deutsches Institut fuer Normung)" },
        { 175, "FCI (Factors Chain International)" },
        { 176, "BR, Banco Central do Brazil" },
        { 177, "AU, LIFA (Life Insurance Federation of Australia)" },
        { 178, "AU, SAA (Standards Association of Australia)" },
        { 179, "US, Air transport association of America" },
        { 181, "Edibuild" },
        { 182, "US, Standard Carrier Alpha Code (Motor)" },
        { 183, "US, American Petroleum Institute" },
        { 184, "AU, ACOS (Australian Chamber of Shipping)" },
        { 999, "ZZZ (Mutually defined)" }
    };

        public static string GetCodeDescription(string code)
        {
            if (String.IsNullOrWhiteSpace(code))
                return "";
            // Convert string to int
            var codeInt = Convert.ToInt32(code);

            if (CodeList.TryGetValue(codeInt, out string description))
            {
                return description;
            }
           return "Invalid code";
        }
    }


}
